import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  Box,
  Button,
  Center,
  Input,
  InputGroup,
  InputLeftAddon,
  Spacer,
  Text,
} from "@chakra-ui/react";
import Link from "next/link";
import { MdLocationPin } from "react-icons/md";
import { BsCalendar2DateFill } from "react-icons/bs";
import { FaCar } from "react-icons/fa";
import CarCard from "../components/CarCard";
import { useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    navigator.geolocation.getCurrentPosition(function (position) {
      console.log(position);
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box backgroundColor={"gray.100"}>
        <Box fontFamily={"Inter"} className="top-menu-bar" textAlign={"right"}>
          <Box
            textColor={"white"}
            pr={"7%"}
            pt={"1"}
            pb={"1"}
            bgColor={"#DE3450"}
          >
            Call: 9825319866
          </Box>
        </Box>

        <Box
          className="main-menu-bar"
          fontFamily={"Inter"}
          display={"flex"}
          bgColor={"white"}
          paddingLeft={"7%"}
          paddingRight={"7%"}
          paddingTop={"8"}
          paddingBottom={"8"}
          fontWeight={"medium"}
        >
          <Box>
            <Image src={"/logo.jpg"} width={"200"} height={"200"}></Image>
          </Box>
          <Spacer />
          <Box display={"flex"} gap={"12"} alignItems={"center"}>
            <Link href={"/"}>Home</Link>
            <Link href={"/"}>Contact</Link>
            <Link href={"/"}>About Us</Link>
            <Link href={"/"}>Vehicles</Link>

            <Button variant={"outline"} colorScheme="red">
              <Link href={"/"}>Login</Link>
            </Button>

            <Button colorScheme="red">
              <Link href={"/"}>Book Now</Link>
            </Button>
          </Box>
        </Box>

        <Box
          className="hero-section"
          height={"650"}
          display={"flex"}
          pl={"7%"}
          pr={"7%"}
          alignItems={"center"}
        >
          <Box width={"50%"}>
            <Text
              fontFamily={"Inter"}
              fontSize={"3xl"}
              fontWeight={"bold"}
              textColor={"#373737"}
            >
              Where Do You Want To Go Today?
            </Text>
            <br></br>
            <form>
              <Box
                fontFamily={"Inter"}
                display={"flex"}
                flexDir={"column"}
                gap={"5"}
                width={"70%"}
              >
                <InputGroup>
                  <InputLeftAddon
                    bgColor={"red"}
                    children={<MdLocationPin color="white" />}
                  ></InputLeftAddon>
                  <Input
                    bgColor={"white"}
                    placeholder="Select destination"
                  ></Input>
                </InputGroup>

                <InputGroup>
                  <InputLeftAddon
                    bgColor={"red"}
                    color={"white"}
                    children={<BsCalendar2DateFill></BsCalendar2DateFill>}
                  ></InputLeftAddon>
                  <Input bgColor={"white"} placeholder="Type date"></Input>
                </InputGroup>

                <InputGroup>
                  <InputLeftAddon
                    bgColor={"red"}
                    color={"white"}
                    children={<FaCar />}
                  ></InputLeftAddon>
                  <Input
                    bgColor={"white"}
                    placeholder="Select Vehicle Type"
                  ></Input>
                </InputGroup>

                <Button colorScheme="red">Confirm Selection</Button>
              </Box>
            </form>
          </Box>
          <Box width={"50%"} display={"flex"} justifyContent={"center"}>
            <Image src={"/car2.png"} height={"2000"} width={"2000"}></Image>
          </Box>
        </Box>
      </Box>
      <Text
        fontFamily={"Inter"}
        fontWeight={"bold"}
        fontSize={"4xl"}
        textAlign={"center"}
        mt={"16"}
      >
        Find Vehicles
      </Text>
      <Box
        marginLeft={"8%"}
        marginRight={"8%"}
        marginTop={"16"}
        marginBottom={"16"}
        display={"flex"}
        justifyContent={"space-around"}
        gap={"16"}
        flexWrap={"wrap"}
      >
        <CarCard image={"/sedan.webp"} title={"Sedan"} />
        <CarCard image={"/hatchback.png"} title={"Hatchback"} />
        <CarCard image={"/brezza.png"} title={"SUV(5-seater))"} />
        <CarCard image={"/suv2.png"} title={"SUV(7-seater)"} />
        <CarCard image={"/hiace.png"} title={"7+ Seater"} />
        <CarCard image={"/tesla.png"} title={"Electric"} />
        <CarCard image={"/rubicon.png"} title={"Off-road"} />
        <Link href={"/"}>
          <CarCard title={"+ See All"} />
        </Link>
      </Box>

      <Box padding={"10"}></Box>
    </>
  );
}
