import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Box, Button, Spacer } from "@chakra-ui/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box fontFamily={"Inter"} className="top-menu-bar" textAlign={"right"}>
        <Box
          textColor={"white"}
          pr={"7%"}
          pt={"1"}
          pb={"1"}
          bgColor={"#DE3450"}
        >
          Call: 9825319866
        </Box>
      </Box>

      <Box
        className="main-menu-bar"
        fontFamily={"Inter"}
        display={"flex"}
        bgColor={"white"}
        paddingLeft={"7%"}
        paddingRight={"7%"}
        paddingTop={"8"}
        paddingBottom={"8"}
        fontWeight={"medium"}
      >
        <Box>
          <Image src={"/logo.jpg"} width={"200"} height={"200"}></Image>
        </Box>
        <Spacer />
        <Box display={"flex"} gap={"12"} alignItems={"center"}>
          <Link href={"/"}>Home</Link>
          <Link href={"/"}>Contact</Link>
          <Link href={"/"}>About Us</Link>
          <Link href={"/"}>Vehicles</Link>

          <Button variant={"outline"} colorScheme="red">
            <Link href={"/"}>Login</Link>
          </Button>

          <Button colorScheme="red">
            <Link href={"/"}>Book Now</Link>
          </Button>
        </Box>
      </Box>
    </>
  );
}
